// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getContrast
double getContrast(NumericMatrix cand_rgb, NumericVector coloring, const arma::sp_mat& adj_mat, double beta);
RcppExport SEXP _MapColoring_getContrast(SEXP cand_rgbSEXP, SEXP coloringSEXP, SEXP adj_matSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cand_rgb(cand_rgbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coloring(coloringSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type adj_mat(adj_matSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(getContrast(cand_rgb, coloring, adj_mat, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MapColoring_getContrast", (DL_FUNC) &_MapColoring_getContrast, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_MapColoring(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
