# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getContrast <- function(cand_rgb, coloring, adj_mat, beta) {
    .Call(`_MapColoring_getContrast`, cand_rgb, coloring, adj_mat, beta)
}

